AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Billing Alerts for your AWS sandbox, creates 2 CFN stacks via 2 Lambda functions to stop or delete resources.

Parameters:
  Email:
    Type: String
    Default: dst-student@datascientest.com
    Description: The Datascientest admin email address to receive alerts per email
  EmailStudent:
    Type: String
    Default: dst-student@datascientest.com
    Description: The Student email address to receive alerts per email
  WarningLevel:
    Type: String
    Default: "150"
    Description: The Warning level of Billing alarm, this would trigger the freeze CodePipeline process
  CriticalLevel:
    Type: String
    Default: "200"
    Description: The Critical level of Billing alarm, this would trigger the nuke CodePipeline process
  S3BucketName:
    Type: String
    Default: "cf-template-datascientest-sandboxes"
    Description: Provide a unique name for the S3 Bucket that will contain the CloudFormation templates for the sandbox management.
  GITHUBToken:
    Type: String
    Default: "*****************"
    Description: Provide a valid GithubToken to fetch templates

Resources:
  FreezeAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: "management"
          Value: "student"
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt FreezeLambdaFunction.Arn
  NukeAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: "management"
          Value: "student"
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt NukeLambdaFunction.Arn

  FreezeLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref FreezeLambdaFunction
      Principal: sns.amazonaws.com

  NukeLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref NukeLambdaFunction
      Principal: sns.amazonaws.com

  FreezeLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Tags:
        - Key: "management"
          Value: "student"
      Handler: index_freeze.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 60
      MemorySize: 2048
      Environment:
        Variables:
          GITHUBToken: !Ref GITHUBToken
          S3Bucket: !Ref S3BucketName
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: index_freeze.zip

  NukeLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Tags:
        - Key: "management"
          Value: "student"
      Handler: index_nuke.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 60
      MemorySize: 2048
      Environment:
        Variables:
          GITHUBToken: !Ref GITHUBToken
          S3Bucket: !Ref S3BucketName
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: index_nuke.zip

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: "management"
          Value: "student"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      Path: "/"
      Policies:
        - PolicyName: SandboxLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - codepipeline:*
                  - sts:*
                  - kms:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - 'sns:Subscribe'
                  - 'sns:Receive'
                  - 'sns:Unsubscribe'
                Resource: "*"

  Budget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetLimit:
          Amount: !Ref WarningLevel
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        # Alerts for student only
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: 25
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref EmailStudent
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: 50
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref EmailStudent
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: 75
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref EmailStudent
        # Alerts for admin and student for WarningLevel
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: !Ref WarningLevel
            ThresholdType: ABSOLUTE_VALUE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref FreezeAlertTopic
            - SubscriptionType: EMAIL
              Address: !Ref Email
            - SubscriptionType: EMAIL
              Address: !Ref EmailStudent
        # Alerts for admin and student for CriticalLevel
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: !Ref CriticalLevel
            ThresholdType: ABSOLUTE_VALUE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref NukeAlertTopic
            - SubscriptionType: EMAIL
              Address: !Ref Email
            - SubscriptionType: EMAIL
              Address: !Ref EmailStudent
      ResourceTags:
        - Key: "management"
          Value: "student"

Outputs:
  FreezeLambdaFunctionName:
    Description: FreezeLambdaFunction function name
    Value: !Ref FreezeLambdaFunction
  FreezeAlertTopicName:
    Description: Freeze SNS topic name
    Value: !GetAtt FreezeAlertTopic.TopicName
  FreezeAlertTopicARN:
    Description: Freeze SNS topic ARN
    Value: !Ref FreezeAlertTopic
  NukeLambdaFunctionName:
    Description: NukeLambdaFunction function name
    Value: !Ref NukeLambdaFunction
  NukeAlertTopicName:
    Description: Nuke SNS topic name
    Value: !GetAtt NukeAlertTopic.TopicName
  NukeAlertTopicARN:
    Description: Nuke SNS topic ARN
    Value: !Ref NukeAlertTopic
